//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.27 at 08:38:36 PM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "greyhope.org/echo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.greyhope.echo;
